### ISSUE TITLE
IAR License Server Firewall

### ISSUE THREAD

**Issue by sharpgeek** [IARSystems/bxarm-docker#3]
I went through the IAR Tech Note explaining that I should poke a hole in the firewall for both sides on the port 5093 for the UDP protocol. But it also says that `ping` is useless as the server does not respond to IGMP packets. How I can be certain that the server is reachable?

**Comment by felipe-iar** [comment]
Hi @sharpgeek,

Your question resulted in a new entry on the [bxarm-docker wiki](https://github.com/IARSystems/bxarm-docker/wiki).

You can access it [here](https://github.com/IARSystems/bxarm-docker/wiki/firewall-5093-udp).
